package com.kidcompass.models;


import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

// Event entity class representing an event. This will store info about the event in the database.
@Entity
public class Event {

    // Primary key for the Event entity, which will be automatically generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;
    private String description;
    private String location;
    private LocalDateTime eventDateTime;

    //A Parent can have many Events.
    @ManyToOne
    @JoinColumn(name="parent_id")
    private Parent parent;

    public Event() {}

    //to create an Event, constructor with required fields
    public Event(String title, String description, String location, LocalDateTime eventDateTime, Parent parent) {
        this.title = title;
        this.description = description;
        this.location = location;
        this.eventDateTime = eventDateTime;
        this.parent = parent;
    }

    //Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public LocalDateTime getEventDateTime() {
        return eventDateTime;
    }

    public void setEventDateTime(LocalDateTime eventDateTime) {
        this.eventDateTime = eventDateTime;
    }

    public Parent getParent() {
        return parent;
    }

    public void setParent(Parent parent) {
        this.parent = parent;
    }
}
