package com.kidcompass.models;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;


//Parent entity class representing a parent and their child. This will store info about the parent and their child in the database.

@Entity
public class Parent {

    //This is the primary key for the Parent entity, which will be automatically generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    //Parent profile information
    private String name;
    private String email;
    private String city;
    private String state;
    private String country;
    private String kidName;
    private Integer kidAge;
    private String kidGender;
    private String kidBio;

    public Parent() {}

    //Constructor
    public Parent(String name, String email, String city, String state, String country, String kidName, Integer kidAge, String kidGender, String kidBio) {
        this.name = name;
        this.email = email;
        this.city = city;
        this.state = state;
        this.country = country;
        this.kidName = kidName;
        this.kidAge = kidAge;
        this.kidGender = kidGender;
        this.kidBio = kidBio;
    }

    //Getters and Setters

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getKidName() {
        return kidName;
    }

    public void setKidName(String kidName) {
        this.kidName = kidName;
    }

    public Integer getKidAge() {
        return kidAge;
    }

    public void setKidAge(Integer kidAge) {
        this.kidAge = kidAge;
    }

    public String getKidGender() {
        return kidGender;
    }

    public void setKidGender(String kidGender) {
        this.kidGender = kidGender;
    }

    public String getKidBio() {
        return kidBio;
    }

    public void setKidBio(String kidBio) {
        this.kidBio = kidBio;
    }
}
